import LegalPage from "@/app/components/legal-page";
import { pageMetadata } from "@/app/lib/site";

const path = "/audit-terms";
export const metadata = pageMetadata({ title: "Free Instagram Audit Terms | Project Monet", description: "Terms for Project Monet’s Free Instagram Audit: eligibility, review scope, exclusions, submitted information, follow-up, and privacy.", path });

export default function Page() {
  return <LegalPage path={path} title="Free Instagram Audit Terms" intro="The Free Instagram Audit is a human account diagnosis. It is not an automated score, a complete free strategy, or a promise of growth." updated="29 August 2026" sections={[
    { heading: "Who can request an Audit", paragraphs: ["A founder, creator, business representative, or authorised decision participant may request an Audit for an Instagram account they are allowed to discuss. You must provide accurate contact and account information.", "Project Monet may decline, limit, or prioritise requests where information is incomplete, the account cannot be reviewed, the request appears abusive or automated, or the service is not a reasonable fit."] },
    { heading: "What Project Monet reviews", bullets: ["Positioning and audience clarity", "Profile structure and next action", "Recent public content", "Obvious growth problems", "Visible conversion gaps", "The clearest opportunities Project Monet can identify from the account and submitted context"] },
    { heading: "What the Audit provides", paragraphs: ["Project Monet will aim to share the clearest useful diagnosis and next recommendation it sees. The depth, format, and timing can vary with the account and information available.", "The Audit does not include a complete strategy, finished scripts, a content calendar, production, implementation, private qualification rules, or unlimited consultation."] },
    { heading: "No result or engagement promise", paragraphs: ["An Audit cannot guarantee reach, followers, DMs, leads, sales, bookings, or another result. Submitting the form does not create a client relationship and does not require either party to enter a paid engagement.", "If Project Monet recommends Standard Management or Viral Mandate, any work starts only under a separate written agreement. Viral Mandate qualification and signed terms are separate from these Audit terms."] },
    { heading: "Information and access", paragraphs: ["You permit Project Monet to review the public Instagram profile identified in the form and use the submitted answers to respond to the request. Do not submit passwords, payment information, confidential client data, or material you are not authorised to share.", "If additional private access would be useful, Project Monet will request it separately. The Audit form never asks for an Instagram password."] },
    { heading: "Contact and follow-up", paragraphs: ["Project Monet may contact you about the Audit, ask a clarifying question, deliver the review, or explain a relevant service. You can say that you do not want further follow-up.", "Information is handled under the Privacy Policy. Current Web3Forms submission records are configured for retention up to 3 years, subject to the policy’s deletion and records terms."] },
    { heading: "Changes", paragraphs: ["Project Monet may update these terms for future Audit requests. The version shown when you submit applies to that request unless a later written agreement says otherwise. Questions can be sent to contact@projectmonet.com."] },
  ]} related={[{ href: "/instagram-audit", label: "Free Instagram Audit" }, { href: "/privacy", label: "Privacy Policy" }, { href: "/terms", label: "Website Terms" }]} />;
}
