import LegalPage from "@/app/components/legal-page";
import { pageMetadata } from "@/app/lib/site";

const path = "/privacy";
export const metadata = pageMetadata({ title: "Privacy Policy | Project Monet", description: "How Project Monet collects, uses, shares, retains, and protects information from its website and Instagram service enquiry forms.", path });

export default function Page() {
  return <LegalPage path={path} title="Privacy Policy" intro="This policy explains what Project Monet collects through this website, why we use it, which providers process it, and the choices available to you." updated="29 August 2026" sections={[
    { heading: "Who this policy covers", paragraphs: ["This policy applies to ProjectMonet.com and the Free Instagram Audit and Viral Mandate qualification forms on the site. Project Monet can be contacted at contact@projectmonet.com.", "It does not govern Instagram, linked websites, or another provider’s service. Their own policies apply when you use them."] },
    { heading: "Information you provide", paragraphs: ["The Free Instagram Audit form can collect your name, email, phone or WhatsApp number, business or creator name, Instagram handle or URL, niche, goals, current resources, decision role, budget openness, optional message, and consent.", "The Viral Mandate form can collect your name, email, business or creator name, Instagram handle or URL, niche, follower and normal-Reel estimates, goals, spokesperson and resource readiness, artificial-growth history, creative-control and revision readiness, cadence, budget, target understanding, optional message, and consent."] },
    { heading: "Information collected with a submission", bullets: ["Form type", "Source page", "Submission time", "UTM source, medium, and campaign when present in the page URL", "A hidden honeypot field used to identify automated spam"], paragraphs: ["We do not intentionally send the answers from your form to analytics."] },
    { heading: "How we use the information", bullets: ["Review the requested Instagram account and the context you provided", "Respond to an Audit request or Viral Mandate application", "Assess which service, if any, appears suitable", "Deliver the clearest Audit opportunities we see", "Maintain reasonable enquiry and consent records", "Prevent spam, abuse, and misuse of the forms", "Improve the clarity and operation of the enquiry process"] },
    { heading: "Web3Forms and service providers", paragraphs: ["The forms use Web3Forms as the submission processor and delivery provider. The public Web3Forms access key identifies the form configuration; it is not a private inbox address.", "Web3Forms receives the submitted fields and routes the message to Project Monet. Hosting and delivery providers, including Vercel, may process technical request data needed to serve and secure the website. Providers may process data in countries other than your own, subject to their terms and safeguards."] },
    { heading: "Retention", paragraphs: ["The current Web3Forms configuration retains submission records for up to 3 years. Project Monet may delete information earlier when it is no longer needed for the request, records, security, or a legal obligation.", "Copies delivered to Project Monet may be retained only as long as reasonably needed to respond, assess fit, maintain business records, resolve disputes, or meet legal requirements."] },
    { heading: "Analytics and cookies", paragraphs: ["No approved analytics Measurement ID is active on the production site at the date of this policy. The site does not intentionally run advertising trackers.", "If optional analytics is added later, consent will be denied by default until a visitor makes a choice, and form answers or other personal information will not be sent as analytics event data. Read the Cookies Policy for the current cookie position."] },
    { heading: "Your choices", paragraphs: ["You can choose not to submit a form and contact Project Monet by email instead. You can ask to access, correct, or delete information connected to your request, subject to identity checks and information that must be retained for legal or security reasons.", "To make a privacy request, email contact@projectmonet.com and identify the request or Instagram account well enough for us to locate the relevant record. Do not send passwords or other account credentials."] },
    { heading: "Security and changes", paragraphs: ["Project Monet uses reasonable technical and organisational controls, including encrypted transport, restrictive browser security headers, input limits, and spam checks. No internet service can promise absolute security.", "We may update this policy when the site, providers, or legal requirements change. The current version and date will remain on this page."] },
  ]} related={[{ href: "/cookies", label: "Cookies Policy" }, { href: "/terms", label: "Website Terms" }, { href: "/audit-terms", label: "Free Audit Terms" }]} />;
}
