import LegalPage from "@/app/components/legal-page";
import { pageMetadata } from "@/app/lib/site";

const path = "/terms";
export const metadata = pageMetadata({ title: "Website Terms | Project Monet", description: "Terms for using ProjectMonet.com, its public content, external links, enquiry forms, pricing information, and service descriptions.", path });

export default function Page() {
  return <LegalPage path={path} title="Website Terms" intro="These terms apply to the public ProjectMonet.com website. Paid services, deliverables, targets, refunds, and client responsibilities are governed by a separate signed agreement." updated="29 August 2026" sections={[
    { heading: "Using the website", paragraphs: ["You may use this website for lawful information, evaluation, and enquiry purposes. Do not interfere with the site, attempt unauthorised access, submit malicious material, overload the forms, or misrepresent your identity or authority."] },
    { heading: "Public information is not a client agreement", paragraphs: ["The website explains Project Monet’s current services in general terms. It is not a proposal, contract, legal opinion, or promise that a specific account will achieve a result.", "A paid engagement begins only when the parties accept the relevant written agreement. That agreement defines scope, payment, responsibilities, approvals, intellectual property, measurement, termination, and any applicable performance terms."] },
    { heading: "Pricing", paragraphs: ["Standard Management is publicly presented from $1,000 per month. Viral Mandate is publicly presented from $2,500 per month, requires qualification, and uses a six-month contract.", "Starting prices do not promise a particular scope. The final price and deliverables depend on the written engagement. Standard Management has no virality guarantee."] },
    { heading: "Viral Mandate", paragraphs: ["Website copy does not create an unconditional viral promise or acceptance for any account. For an eligible client, the agreed viral reach, measurement, client responsibilities, creative-control boundaries, and any 50% refund eligibility must be defined in the signed Viral Mandate agreement.", "If website text and a signed client agreement differ, the signed agreement governs that engagement."] },
    { heading: "Content and intellectual property", paragraphs: ["Project Monet owns or licenses the website design, text, code, marks, and approved media unless stated otherwise. You may read and share links to public pages. Do not copy, resell, republish, or create misleading derivative material from substantial parts of the site without permission.", "Instagram and other third-party names and marks belong to their respective owners. Project Monet is not presented as Instagram or Meta."] },
    { heading: "External links", paragraphs: ["The website links to Instagram profiles, Project Monet’s Websites service, and other pages outside this site. Project Monet is not responsible for the availability, security, content, or policies of an external service."] },
    { heading: "Availability and accuracy", paragraphs: ["We aim to keep public descriptions accurate and the website available. Information may be corrected or updated, and temporary interruptions can occur. Do not rely on a cached page as the current commercial agreement."] },
    { heading: "Responsibility", paragraphs: ["To the extent permitted by applicable law, Project Monet is not responsible for indirect loss caused only by use of public website information or an external link. Nothing on this page excludes responsibility that cannot legally be excluded.", "Questions about these terms can be sent to contact@projectmonet.com."] },
  ]} related={[{ href: "/privacy", label: "Privacy Policy" }, { href: "/cookies", label: "Cookies Policy" }, { href: "/audit-terms", label: "Free Audit Terms" }]} />;
}
