import LegalPage from "@/app/components/legal-page";
import { pageMetadata } from "@/app/lib/site";

const path = "/cookies";
export const metadata = pageMetadata({ title: "Cookies Policy | Project Monet", description: "How Project Monet uses consent-gated Google Analytics, essential website storage, and browser choices.", path });

export default function Page() {
  return <LegalPage path={path} title="Cookies Policy" intro="ProjectMonet.com keeps tracking optional and minimal. This page explains the storage the site may use and how you control Google Analytics." updated="8 September 2026" sections={[
    { heading: "What cookies are", paragraphs: ["Cookies are small values a website or provider can store in a browser. Similar technologies include local storage and other identifiers used to remember state, secure a request, or measure use."] },
    { heading: "Current production position", paragraphs: ["Project Monet uses Google Analytics 4 as optional analytics. The Google Analytics tag loads only after you select Accept analytics. Selecting Decline leaves it unloaded.", "The form wizard keeps answers in the page while it is open. It does not save those answers to analytics or persistent browser storage. The site uses temporary session storage for the first landing page, referring page, and UTM source, medium, campaign, and content so this context can accompany a form submission. This first-touch record expires when the browser session ends and is not used for cross-site advertising."] },
    { heading: "Essential technology", paragraphs: ["The website and its hosting or security providers may use strictly necessary technical storage or request data to deliver pages, prevent abuse, balance traffic, or maintain security. These functions are not used by Project Monet to build advertising profiles.", "External links, Instagram, Web3Forms, Vercel, and other third-party services have their own cookie and privacy practices when you interact with them."] },
    { heading: "Optional analytics", paragraphs: ["When accepted, Google Analytics can set or read analytics identifiers and measure page views, scrolls, outbound clicks, site searches, file downloads, supported video engagement, form interactions, Audit CTA clicks, Viral qualification CTA clicks, successful form submissions, the Websites link, and click-to-email.", "A successful Audit request or Viral Mandate application is also recorded as a generate_lead event. Analytics events do not contain form answers, email addresses, phone numbers, Instagram handles, or other personal information."] },
    { heading: "Your choice and storage", paragraphs: ["The site stores your accepted or declined analytics choice in your browser’s local storage. If you accept, Google Analytics may also use analytics cookies. If you decline, the Google Analytics tag is not loaded.", "You can change the choice by clearing ProjectMonet.com site data in your browser and revisiting the site. Most browsers also let you view, block, or delete cookies and local storage. Blocking strictly necessary technology may affect how a service works."] },
    { heading: "Changes and contact", paragraphs: ["We will update this page if the site begins using new cookie categories or analytics tools. Questions can be sent to contact@projectmonet.com."] },
  ]} related={[{ href: "/privacy", label: "Privacy Policy" }, { href: "/terms", label: "Website Terms" }, { href: "/audit-terms", label: "Free Audit Terms" }]} />;
}
